# This is a docker-compose file for developing SQE_API
# Start it up and you get all the services
version: '3.7'

services:
    sqe-database:
        image: qumranica/sqe-database:0.23.2
        container_name: SQE_Database
        # These environment variables match the default db connection settings for the project.
        environment:
            - MYSQL_ROOT_PASSWORD=none
            - MYSQL_USER=sqe_user
            - MYSQL_PASSWORD=mysecretpw
            - MYSQL_DATABASE=SQE
        expose:
            - "3306"
        ports:
            - "3307:3306"
        networks:
            - sqe_api

networks:
    sqe_api:
