<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\sqe_api\sqe_api.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="PlexDiff" Version="1.6.5" />
    </ItemGroup>

</Project>
