language: csharp
dist: bionic
mono: none
dotnet: 2.2
services: docker

before_install:
- docker-compose -f docker-http-server/dev/docker-compose.yml pull
- docker-compose -f docker-http-server/dev/docker-compose.yml build
- docker-compose -f docker-http-server/dev/docker-compose.yml up -d

install:
- dotnet restore
- dotnet tool install -g coveralls.net --version 1.0.0

script:
- dotnet build
- dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput='../coverage.xml' /p:Exclude="[xunit.*]*%2c[*]SQE.SqeHttpApi.Server.Helpers.EmailSender%2c[*]SQE.SqeHttpApi.Server.Helpers.StartupChecks%2c[*]SQE.SqeHttpApi.Server.Program%2c[*]SQE.SqeHttpApi.DataAccess.Helpers.ApiException%2c[*]SQE.SqeHttpApi.DataAccess.Helpers.StandardErrors%2c[*]SQE.SqeHttpApi.DataAccess.DbConnectionBase.ReliableMySqlDbCommand%2c[*]SQE.SqeHttpApi.DataAccess.DbConnectionBase.ReliableMySqlConnection"
- ~/.dotnet/tools/csmacnz.Coveralls --opencover -i ./coverage.xml --commitId $TRAVIS_COMMIT --commitBranch $TRAVIS_BRANCH --commitAuthor "$REPO_COMMIT_AUTHOR" --commitEmail "$REPO_COMMIT_AUTHOR_EMAIL" --commitMessage "$REPO_COMMIT_MESSAGE" --jobId $TRAVIS_JOB_ID  --serviceName "travis-ci" --useRelativePaths