/*
 * This file is automatically generated by the GenerateTestRequestObjects
 * project in the Utilities folder. Do not edit this file directly as
 * its contents may be overwritten at any point.
 */

namespace SQE.ApiTest.ApiRequests
{
	public enum ListenerMethods
	{
		CreatedArtefact
		, UpdatedArtefact
		, CreatedArtefactGroup
		, DeletedArtefact
		, DeletedArtefactGroup
		, UpdatedArtefactGroup
		, RequestedEditor
		, CreatedEditor
		, CreatedEdition
		, UpdatedEdition
		, DeletedEdition
		, CreatedImagedObject
		, DeletedImagedObject
		, CreatedRoisBatch
		, EditedRoisBatch
		, UpdatedRoisBatch
		, DeletedRoi
		, CreatedScribalFontInfo
		, CreatedScribalFontKerningPair
		, CreatedScribalFontGlyph
		, UpdatedScribalFontInfo
		, DeletedScribalFont
		, DeletedScribalFontKerningPair
		, DeletedScribalFontGlyph
		, CreatedAttribute
		, CreatedSignInterpretation
		, UpdatedSignInterpretations
		, UpdatedSignInterpretation
		, DeletedAttribute
		, DeletedSignInterpretation
		, UpdatedAttribute
		, CreatedTextFragment
		,
	}
}
