# This docker-compose file is for deploying a fully working backend

version: '3.7'

services:
    sqe-database:
        image: qumranica/sqe-database:latest
        container_name: SQE_Database
        environment:
            - MYSQL_ROOT_PASSWORD=none
            - MYSQL_DATABASE=SQE_DEV
        expose:
            - "3306"
        ports:
            - "3307:3306"
        networks:
            - sqe_api

    sqe-http:
        container_name: SQE_HTTP_API
        build: ./
        restart: always
        ports:
            - 5000:5000
        environment:
            - MYSQL_ROOT_PASSWORD=none
            - MYSQL_DATABASE=SQE_DEV
            - MYSQL_HOST=sqe-database
            - MYSQL_PORT=3306
            - DOTNET_CLI_TELEMETRY_OPTOUT=1
        depends_on:
            - sqe-database
        networks:
            - sqe_api

networks:
    sqe_api:
