# This docker-compose file is for deploying a fully working backend

version: '3.7'

services:
    sqe-database:
        image: qumranica/sqe-database:0.9.12
        container_name: SQE_Database
        environment:
            - MYSQL_ROOT_PASSWORD=none
            - MYSQL_DATABASE=SQE_DEV
        expose:
            - "3306"
        ports:
            - "3307:3306"
        networks:
            - sqe_api

    sqe-http:
        container_name: SQE_HTTP_API
        build:
            # Since the Dockerfile is no longer at the root, reset the context two folder higher from this docker-compose.yml
            # It would provide a more optimized build if the context folder contained only "data-access" and "sqe-http-api".
            context: ../../
            # Provide the relative path from the context to the Dockerfile
            dockerfile: docker/Dockerfile
        restart: always
        ports:
            - 5000:5000
        environment:
            - MYSQL_ROOT_PASSWORD=none
            - MYSQL_DATABASE=SQE_DEV
            - MYSQL_HOST=sqe-database
            - MYSQL_PORT=3306
            - DOTNET_CLI_TELEMETRY_OPTOUT=1
            # For system emails to work you need to add credentials (using gmail for simplicity right now)
            - SQE_GMAIL_USERNAME=your_gmail_username_here_without_@.gmail.com
            - SQE_GMAIL_PASSWORD=your_gmail_password_here
        depends_on:
            - sqe-database
        networks:
            - sqe_api

networks:
    sqe_api:
