/*
 * Do not edit this file directly!
 * This hub class is autogenerated by the `sqe-realtime-hub-builder` project
 * based on the controllers in the `sqe-api-server` project. Changes made
 * there will automatically be incorporated here the next time the
 * `sqe-realtime-hub-builder` is run.
 */

using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using SQE.API.DTO;
using SQE.API.Server.Services;
using Microsoft.AspNetCore.SignalR;

using SQE.DatabaseAccess.Helpers;

using System.Text.Json;

using SQE.API.Server.Helpers;

namespace SQE.API.Server.RealtimeHubs
{
    public partial class MainHub
    {
/// <summary>
	///  Runs a health check on the database.
	/// </summary>
[Authorize]
public async Task<ServiceStatusDTO> GetV1AdminDbAccessible()

    {
        try
        {
             return  await _adminService.GetDatabaseStatusAsync(await _userService.GetCurrentUserObjectAsync(null));
        }
        catch (ApiException err)
        {
            throw new HubException(JsonSerializer.Serialize(new HttpExceptionMiddleware.ApiExceptionError(nameof(err), err.Error, err is IExceptionWithData exceptionWithData ? exceptionWithData.CustomReturnedData : null)));
        }
    }


/// <summary>
	///  Attempts to send an email to the requesting user.
	/// </summary>
[Authorize]
public async Task<ServiceStatusDTO> GetV1AdminEmailerFunctioning()

    {
        try
        {
             return  await _adminService.GetEmailStatusAsync(await _userService.GetCurrentUserObjectAsync(null));
        }
        catch (ApiException err)
        {
            throw new HubException(JsonSerializer.Serialize(new HttpExceptionMiddleware.ApiExceptionError(nameof(err), err.Error, err is IExceptionWithData exceptionWithData ? exceptionWithData.CustomReturnedData : null)));
        }
    }


	}
}
