/*
 * Do not edit this file directly!
 * This hub class is autogenerated by the `sqe-realtime-hub-builder` project
 * based on the controllers in the `sqe-api-server` project. Changes made
 * there will automatically be incorporated here the next time the
 * `sqe-realtime-hub-builder` is run.
 */

using Microsoft.AspNetCore.SignalR;
using SQE.API.Server.Services;

namespace SQE.API.Server.RealtimeHubs
{
	public partial class MainHub : Hub<ISQEClient>
	{
		private readonly IArtefactService           _artefactService;
		private readonly ICatalogService            _catalogueService;
		private readonly IEditionService            _editionService;
		private readonly IImagedObjectService       _imagedObjectService;
		private readonly IImageService              _imageService;
		private readonly IRoiService                _roiService;
		private readonly IScriptService             _scriptService;
		private readonly ISearchService             _searchService;
		private readonly ISignInterpretationService _signInterpretationService;
		private readonly ITextService               _textService;
		private readonly IUserService               _userService;
		private readonly IUtilService               _utilService;
		private readonly IWordService               _wordService;

		public MainHub(
				IRoiService                  roiService
				, IUserService               userService
				, IEditionService            editionService
				, ITextService               textService
				, IArtefactService           artefactService
				, ISignInterpretationService signInterpretationService
				, IImagedObjectService       imagedObjectService
				, IImageService              imageService
				, IScriptService             scriptService
				, ICatalogService            catalogueService
				, IUtilService               utilService
				, ISearchService             searchService
				, IWordService               wordService)
		{
			_roiService = roiService;
			_userService = userService;
			_editionService = editionService;
			_textService = textService;
			_artefactService = artefactService;
			_signInterpretationService = signInterpretationService;
			_imagedObjectService = imagedObjectService;
			_imageService = imageService;
			_scriptService = scriptService;
			_catalogueService = catalogueService;
			_utilService = utilService;
			_searchService = searchService;
			_wordService = wordService;
		}
	}
}
