/*
 * Do not edit this file directly!
 * This hub class is autogenerated by the `sqe-realtime-hub-builder` project
 * based on the controllers in the `sqe-api-server` project. Changes made
 * there will automatically be incorporated here the next time the
 * `sqe-realtime-hub-builder` is run.
 */

using Microsoft.AspNetCore.SignalR;
using SQE.API.Server.Services;

namespace SQE.API.Server.RealtimeHubs;

public partial class MainHub : Hub<ISQEClient>
{
	private readonly IArtefactService           _artefactService;
	private readonly ICatalogService            _catalogueService;
	private readonly IEditionService            _editionService;
	private readonly IImageService              _imageService;
	private readonly IImagedObjectService       _imagedObjectService;
	private readonly IRoiService                _roiService;
	private readonly IScriptService             _scriptService;
	private readonly ISearchService             _searchService;
	private readonly ISignInterpretationService _signInterpretationService;
	private readonly ITextService               _textService;
	private readonly IUserService               _userService;
	private readonly IUtilService               _utilService;
	private readonly IWordService               _wordService;

	public MainHub(
			ITextService                 textService
			, IUserService               userService
			, IScriptService             scriptService
			, IEditionService            editionService
			, IWordService               wordService
			, IImagedObjectService       imagedObjectService
			, IImageService              imageService
			, ISearchService             searchService
			, IRoiService                roiService
			, ISignInterpretationService signInterpretationService
			, ICatalogService            catalogueService
			, IArtefactService           artefactService
			, IUtilService               utilService)
	{
		_textService = textService;
		_userService = userService;
		_scriptService = scriptService;
		_editionService = editionService;
		_wordService = wordService;
		_imagedObjectService = imagedObjectService;
		_imageService = imageService;
		_searchService = searchService;
		_roiService = roiService;
		_signInterpretationService = signInterpretationService;
		_catalogueService = catalogueService;
		_artefactService = artefactService;
		_utilService = utilService;
	}
}
