/*
 * Do not edit this file directly!
 * This hub class is autogenerated by the `sqe-realtime-hub-builder` project
 * based on the controllers in the `sqe-api-server` project. Changes made
 * there will automatically be incorporated here the next time the 
 * `sqe-realtime-hub-builder` is run.
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using SQE.API.DTO;
using SQE.API.Server.Services;
using Microsoft.AspNetCore.SignalR;

using SQE.DatabaseAccess.Helpers;

using System.Text.Json;

using SQE.API.Server.Helpers;

namespace SQE.API.Server.RealtimeHubs
{
    public partial class MainHub
    {
        /// <summary>
        /// Retrieve a list of all possible attributes for an edition
        /// </summary>
        /// <param name="editionId">The ID of the edition being searched</param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        [Authorize]
        public async Task<AttributeListDTO> GetV1EditionsEditionIdSignInterpretationsAttributes(uint editionId)

        {
            try
            {
                throw new NotImplementedException(); //Not Implemented              
            }
            catch (ApiException err)
            {
                throw new HubException(JsonSerializer.Serialize(new HttpExceptionMiddleware.ApiExceptionError(nameof(err), err.Error, err is IExceptionWithData exceptionWithData ? exceptionWithData.CustomReturnedData : null)));
            }
        }


        /// <summary>
        /// Retrieve a list of all possible attributes for an edition
        /// </summary>
        /// <param name="editionId">The ID of the edition being edited</param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        [Authorize]
        public async Task<AttributeDTO> PostV1EditionsEditionIdSignInterpretationsAttributes(uint editionId, CreateAttributeDTO newAttribute)

        {
            try
            {
                throw new NotImplementedException(, clientId: Context.ConnectionId); //Not Implemented              
            }
            catch (ApiException err)
            {
                throw new HubException(JsonSerializer.Serialize(new HttpExceptionMiddleware.ApiExceptionError(nameof(err), err.Error, err is IExceptionWithData exceptionWithData ? exceptionWithData.CustomReturnedData : null)));
            }
        }


        /// <summary>
        /// Delete an attribute from an edition
        /// </summary>
        /// <param name="editionId">The ID of the edition being edited</param>
        /// <param name="attributeId">The ID of the attribute to delete</param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        [Authorize]
        public async Task DeleteV1EditionsEditionIdSignInterpretationsAttributesAttributeId(uint editionId, uint attributeId)

        {
            try
            {
                throw new NotImplementedException(, clientId: Context.ConnectionId); //Not Implemented              
            }
            catch (ApiException err)
            {
                throw new HubException(JsonSerializer.Serialize(new HttpExceptionMiddleware.ApiExceptionError(nameof(err), err.Error, err is IExceptionWithData exceptionWithData ? exceptionWithData.CustomReturnedData : null)));
            }
        }


        /// <summary>
        /// Change the details of an attribute in an edition
        /// </summary>
        /// <param name="editionId">The ID of the edition being edited</param>
        /// <param name="attributeId">The ID of the attribute to update</param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        [Authorize]
        public async Task<AttributeDTO> PutV1EditionsEditionIdSignInterpretationsAttributesAttributeId(uint editionId, uint attributeId, CreateAttributeDTO updatedAttribute)

        {
            try
            {
                throw new NotImplementedException(, clientId: Context.ConnectionId); //Not Implemented              
            }
            catch (ApiException err)
            {
                throw new HubException(JsonSerializer.Serialize(new HttpExceptionMiddleware.ApiExceptionError(nameof(err), err.Error, err is IExceptionWithData exceptionWithData ? exceptionWithData.CustomReturnedData : null)));
            }
        }


        /// <summary>
        /// Creates a new sign interpretation 
        /// </summary>
        /// <param name="editionId">ID of the edition being changed</param>
        /// <param name="newSignInterpretation">New sign interpretation data to be added</param>
        /// <returns>The new sign interpretation</returns>
        [Authorize]
        public async Task<SignInterpretationDTO> PostV1EditionsEditionIdSignInterpretations(uint editionId, uint signInterpretationId, SignInterpretationCreateDTO newSignInterpretation)

        {
            try
            {
                throw new NotImplementedException(, clientId: Context.ConnectionId); //Not Implemented              
            }
            catch (ApiException err)
            {
                throw new HubException(JsonSerializer.Serialize(new HttpExceptionMiddleware.ApiExceptionError(nameof(err), err.Error, err is IExceptionWithData exceptionWithData ? exceptionWithData.CustomReturnedData : null)));
            }
        }


        /// <summary>
        /// Deletes the sign interpretation in the route. The endpoint automatically manages the sign stream
        /// by connecting all the deleted sign's next and previous nodes.
        /// </summary>
        /// <param name="editionId">ID of the edition being changed</param>
        /// <param name="signInterpretationId">ID of the sign interpretation being deleted</param>
        /// <returns>Ok or Error</returns>
        [Authorize]
        public async Task DeleteV1EditionsEditionIdSignInterpretationsSignInterpretationId(uint editionId, uint signInterpretationId)

        {
            try
            {
                throw new NotImplementedException(, clientId: Context.ConnectionId); //Not Implemented              
            }
            catch (ApiException err)
            {
                throw new HubException(JsonSerializer.Serialize(new HttpExceptionMiddleware.ApiExceptionError(nameof(err), err.Error, err is IExceptionWithData exceptionWithData ? exceptionWithData.CustomReturnedData : null)));
            }
        }


        /// <summary>
        /// Updates the commentary of a sign interpretation
        /// </summary>
        /// <param name="editionId">ID of the edition being changed</param>
        /// <param name="signInterpretationId">ID of the sign interpretation whose commentary is being changed</param>
        /// <param name="string">The new commentary for the sign interpretation</param>
        /// <returns>Ok or Error</returns>
        [Authorize]
        public async Task PutV1EditionsEditionIdSignInterpretationsSignInterpretationIdCommentary(uint editionId, uint signInterpretationId, string commentary)

        {
            try
            {
                throw new NotImplementedException(, clientId: Context.ConnectionId);  //Not Implemented              
            }
            catch (ApiException err)
            {
                throw new HubException(JsonSerializer.Serialize(new HttpExceptionMiddleware.ApiExceptionError(nameof(err), err.Error, err is IExceptionWithData exceptionWithData ? exceptionWithData.CustomReturnedData : null)));
            }
        }


        /// <summary>
        /// This adds a new attribute to the specified sign interpretation.
        /// </summary>
        /// <param name="editionId">ID of the edition being changed</param>
        /// <param name="signInterpretationId">ID of the sign interpretation for adding a new attribute</param>
        /// <param name="newSignInterpretationAttributes">Details of the attribute to be added</param>
        /// <returns>The updated sign interpretation</returns>
        [Authorize]
        public async Task<SignInterpretationDTO> PostV1EditionsEditionIdSignInterpretationsSignInterpretationIdAttributes(uint editionId, uint signInterpretationId, InterpretationAttributeCreateListDTO newSignInterpretationAttributes)

        {
            try
            {
                throw new NotImplementedException(, clientId: Context.ConnectionId);  //Not Implemented              
            }
            catch (ApiException err)
            {
                throw new HubException(JsonSerializer.Serialize(new HttpExceptionMiddleware.ApiExceptionError(nameof(err), err.Error, err is IExceptionWithData exceptionWithData ? exceptionWithData.CustomReturnedData : null)));
            }
        }


        /// <summary>
        /// This changes the values of the specified sign interpretation attribute,
        /// mainly used to change commentary.
        /// </summary>
        /// <param name="editionId">ID of the edition being changed</param>
        /// <param name="signInterpretationId">ID of the sign interpretation being altered</param>
        /// <param name="attributeId">Id of the attribute to be altered</param>
        /// <param name="alteredSignInterpretationAttribute">New details of the attribute</param>
        /// <returns>The updated sign interpretation</returns>
        [Authorize]
        public async Task<SignInterpretationDTO> PutV1EditionsEditionIdSignInterpretationsSignInterpretationIdAttributesAttributeId(uint editionId, uint signInterpretationId, uint attributeId, InterpretationAttributeCreateDTO alteredSignInterpretationAttribute)

        {
            try
            {
                throw new NotImplementedException(, clientId: Context.ConnectionId);  //Not Implemented              
            }
            catch (ApiException err)
            {
                throw new HubException(JsonSerializer.Serialize(new HttpExceptionMiddleware.ApiExceptionError(nameof(err), err.Error, err is IExceptionWithData exceptionWithData ? exceptionWithData.CustomReturnedData : null)));
            }
        }


        /// <summary>
        /// This deletes the specified attribute from the specified sign interpretation.
        /// </summary>
        /// <param name="editionId">ID of the edition being changed</param>
        /// <param name="signInterpretationId">ID of the sign interpretation being alteres</param>
        /// <param name="attributeId">Id of the attribute being removed</param>
        /// <returns>Ok or Error</returns>
        [Authorize]
        public async Task DeleteV1EditionsEditionIdSignInterpretationsSignInterpretationIdAttributesAttributeId(uint editionId, uint signInterpretationId, uint attributeId)

        {
            try
            {
                throw new NotImplementedException(, clientId: Context.ConnectionId);  //Not Implemented              
            }
            catch (ApiException err)
            {
                throw new HubException(JsonSerializer.Serialize(new HttpExceptionMiddleware.ApiExceptionError(nameof(err), err.Error, err is IExceptionWithData exceptionWithData ? exceptionWithData.CustomReturnedData : null)));
            }
        }


    }
}
