/*
 * Do not edit this file directly!
 * This hub class is autogenerated by the `sqe-realtime-hub-builder` project
 * based on the controllers in the `sqe-api-server` project. Changes made
 * there will automatically be incorporated here the next time the 
 * `sqe-realtime-hub-builder` is run.
 */

using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using SQE.API.DTO;
using SQE.API.Server.Services;
using Microsoft.AspNetCore.SignalR;

namespace SQE.API.Server.RealtimeHubs
{
    public partial class MainHub
    {
        /// <summary>
        ///     Checks a WKT polygon to ensure validity. If the polygon is invalid,
        ///     it attempts to construct a valid polygon that matches the original
        ///     as closely as possible.
        /// </summary>
        /// <param name="payload">JSON object with the WKT polygon to validate</param>
        [Authorize]
        public async Task PostV1UtilsValidateWkt(WktPolygonDTO payload)
        {
            await _utilService.ValidateWktPolygonAsync(payload.wktPolygon, clientId: Context.ConnectionId);
        }

    }
}
