name: Build and publish Docker Image
on:
  push:
    tags:
      - v*

jobs:
  docker-image:
    runs-on: ubuntu-latest
    name: Create the SQE Docker Image
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        env:
          REF: ${{ github.ref }}
        run: |
          export VERSION="${REF##*/v}"
          docker build --no-cache -t qumranica/sqe-http-api:${VERSION} -f ./docker/Dockerfile .
          docker push qumranica/sqe-http-api:${VERSION}
