name: Build and publish Docker Image
on:
  push:
    tags:
      - v*

jobs:
  docker-image:
    runs-on: ubuntu-latest
    name: Create the SQE Docker Image
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        env:
          REF: ${{ github.ref }}
        run: export VERSION="${REF##*/v}"

      - name: Build docker image
        run: docker build --no-cache -t qumranica/sqe-http-api:${VERSION} -f ./docker/Dockerfile .

    #   - name: Login to DockerHub
    #     uses: docker/login-action@v2
    #     with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}

    #   - name: Push image to DockerHub
    #     run: docker push -t qumranica/sqe-http=api:${VERSION}

